name: Testing for checkout
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing for checkout
    - uses: actions/checkout@v3
    steps:
      - name: Custom actions
        run: echo aman

