name: Testing for checkout
on:
  push:
    branches:
      "*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing for checkout
    steps:
      - name: Custom actions
        runs: echo aman

