name: zerro scanner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: starting scanner
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Started Vulnerability Scanner zerro
        run: |
          git clone https://github.com/theamanrawat/zerro.git
          cd zerro
          pip install -r requirements.txt
          sleep 20
          python zerro.py